import './portal.css';
import './rehearsal.css';
import { formatBytes, getSongs, loadJson, saveJson } from './db.js';
const SCHEDULE_KEY='halbi.schedule', NOTICE_KEY='halbi.notices', POSTS_KEY='halbi.posts', RSVP_KEY='halbi.rsvp';
const dateFmt=new Intl.DateTimeFormat('ko-KR',{month:'long',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit'});
function updateClock(){const now=new Date();document.querySelector('#today-label').textContent=new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(now);document.querySelector('#clock-time').textContent=now.toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'});}updateClock();setInterval(updateClock,30000);
const schedule=loadJson(SCHEDULE_KEY,{});if(schedule.date){document.querySelector('#rehearsal-date').textContent=dateFmt.format(new Date(schedule.date));}document.querySelector('#rehearsal-venue').textContent=schedule.venue||'장소를 등록해주세요.';document.querySelector('#rehearsal-note').textContent=schedule.note||'';
const savedRsvp=localStorage.getItem(RSVP_KEY);document.querySelectorAll('[data-rsvp]').forEach((button)=>{button.classList.toggle('active',button.dataset.rsvp===savedRsvp);button.addEventListener('click',()=>{localStorage.setItem(RSVP_KEY,button.dataset.rsvp);document.querySelectorAll('[data-rsvp]').forEach(b=>b.classList.remove('active'));button.classList.add('active');document.querySelector('#rsvp-feedback').textContent=`${button.dataset.rsvp}(으)로 응답했습니다.`;});});
function songRows(songs, emptyMessage){return songs.map((song,i)=>`<div class="setlist-row"><span class="track-index">${String(i+1).padStart(2,'0')}</span><div class="track-title"><b>${esc(song.title)}</b><small>${esc(song.artist)}${song.fileName?` · ${esc(song.fileName)} · ${formatBytes(song.fileSize)}`:''}</small></div><span class="track-meta">${song.bpm||'—'} BPM · ${esc(song.key||'—')} · ${song.progress||0}%</span>${song.file?`<audio controls preload="metadata" src="${URL.createObjectURL(song.file)}">오디오를 재생할 수 없습니다.</audio>`:'<span class="no-audio">MP3 없음</span>'}</div>`).join('')||`<p class="empty">${emptyMessage}</p>`;}
async function renderSetlist(){const songs=(await getSongs()).sort((a,b)=>(b.progress||0)-(a.progress||0));const vocal=songs.filter(song=>song.session==='vocal');const wishlist=songs.filter(song=>song.session==='wishlist');document.querySelector('#hub-song-count').textContent=`${vocal.length+wishlist.length} TRACKS`;document.querySelector('#cover-vocal-list').innerHTML=songRows(vocal,'Admin에서 보컬 연습/공연곡을 선택해주세요.');document.querySelector('#wishlist-list').innerHTML=songRows(wishlist,'Admin에서 Wish List 곡을 선택해주세요.');}
function renderNotices(){const notices=loadJson(NOTICE_KEY,[]);document.querySelector('#notice-list').innerHTML=notices.map(n=>`<article class="notice"><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p><time>${new Date(n.createdAt).toLocaleString('ko-KR')}</time></article>`).join('')||'<p class="empty">등록된 공지가 없습니다.</p>';}
function renderPosts(){const posts=loadJson(POSTS_KEY,[]);document.querySelector('#post-list').innerHTML=posts.map(p=>`<article class="post"><b>${esc(p.author)}</b><p>${esc(p.message)}</p><time>${new Date(p.createdAt).toLocaleString('ko-KR')}</time></article>`).join('')||'<p class="empty">첫 메시지를 남겨보세요.</p>';}
document.querySelector('#post-form').addEventListener('submit',(e)=>{e.preventDefault();const form=e.currentTarget;const posts=loadJson(POSTS_KEY,[]);posts.unshift({...Object.fromEntries(new FormData(form)),createdAt:new Date().toISOString()});saveJson(POSTS_KEY,posts.slice(0,50));form.reset();renderPosts();});
function esc(value=''){const div=document.createElement('div');div.textContent=value;return div.innerHTML;}renderSetlist();renderNotices();renderPosts();
